import { BrowserRouter as Router, Routes, Route, Link } from "react-router-dom";
import "./App.css";

function PrivacyPolicy() {
  return (
    <div className="privacy-policy">
      <h1>PRIVACY POLICY</h1>
      <p>
        Welcome to KinetiCare.ai, a digital rehabilitation platform designed to
        prevent injury and support upper extremity recovery through guided
        exercise videos, audio instructions, and AI-powered performance feedback.
        Your privacy is important to us. This Privacy Policy explains how we
        collect, use, and protect your information when you use our app.
      </p>
      <h2>Information We Collect</h2>
      <p>
        We collect the following types of information to provide and improve our
        services:
      </p>
      <ul>
        <li>
          <strong>User-Generated Content</strong>
          <ul>
            <li>Recorded exercise attempts (video and/or audio)</li>
            <li>Performance data generated by AI comparison tools</li>
          </ul>
        </li>
        <li>
          <strong>App Usage Data</strong>
          <ul>
            <li>
              Interaction logs (e.g., which exercises were viewed or completed)
            </li>
            <li>Device type, operating system, and app version</li>
          </ul>
        </li>
        <li>
          <strong>Optional Personal Information</strong>
          <ul>
            <li>
              Name, email address, or other identifiers if voluntarily provided
            </li>
          </ul>
        </li>
      </ul>
      <h2>Device Permissions</h2>
      <p>
        To enable core features of KinetiCare.ai, the app requests the following
        permissions:
      </p>
      <ul>
        <li>
          <strong>Camera Access:</strong> Required to record your exercise
          attempts for AI analysis and performance feedback. Camera access is
          only activated when you choose to record an exercise and is never used
          without your explicit action.
        </li>
        <li>
          <strong>Microphone Access:</strong> Required to capture audio
          instructions and provide audio-based feedback during exercises.
          Microphone access is only used during recording sessions that you
          initiate.
        </li>
      </ul>
      <p>
        You can manage these permissions through your device settings at any
        time. Denying these permissions may limit certain app functionality,
        such as the ability to receive personalized AI feedback on your exercise
        form.
      </p>
      <h2>How We Use Your Information</h2>
      <ul>
        <li>Deliver personalized exercise recommendations</li>
        <li>Provide AI-generated feedback on your performance</li>
        <li>Improve app functionality and user experience</li>
        <li>
          Communicate updates, support, or relevant health content (if opted in)
        </li>
      </ul>
      <h2>AI Analysis and Performance Grading</h2>
      <p>
        When you choose to record your exercise attempts, our AI tools analyze
        your movements against standard models to provide feedback and grading.
        These recordings are stored securely and are only used for your personal
        rehabilitation progress unless you give explicit consent for broader use
        (e.g., research or training).
      </p>
      <h2>Data Protection and Security</h2>
      <p>We implement industry-standard safeguards to protect your data, including:</p>
      <ul>
        <li>End-to-end encryption for video and audio uploads</li>
        <li>Secure storage of AI-generated performance data</li>
        <li>Role-based access controls for internal staff</li>
      </ul>
      <h2>Sharing of Protected Health Information (PHI)</h2>
      <p>
        We do not share any protected health information (PHI) with third parties
        without your explicit written consent. This includes:
      </p>
      <ul>
        <li>Exercise recordings</li>
        <li>AI-generated performance grades</li>
      </ul>
      <p>
        If you choose to share your data with a healthcare provider, caregiver, or
        research team, we will facilitate secure transfer only with your
        permission.
      </p>
      <h2>Your Rights and Choices</h2>
      <ul>
        <li>Access and review your data</li>
        <li>Request deletion of your recordings or personal information</li>
        <li>Withdraw consent for data sharing at any time</li>
        <li>Opt out of non-essential communications</li>
      </ul>
      <p>
        To exercise these rights, contact us at{" "}
        <a href="mailto:Dr.W@KinetiCare.ai">Dr.W@KinetiCare.ai</a>.
      </p>
      <h2>Children's Privacy</h2>
      <p>
        This app is not intended for use by individuals under the age of 13. We
        do not knowingly collect personal information from children without
        parental consent.
      </p>
      <h2>Changes to This Policy</h2>
      <p>
        We may update this Privacy Policy as our app evolves. We will notify you
        of significant changes via in-app alerts or email (if provided).
      </p>
      <h2>Contact Us</h2>
      <p>
        If you have questions or concerns about this Privacy Policy or your
        data, please reach out to us at{" "}
        <a href="mailto:Dr.W@KinetiCare.ai">Dr.W@KinetiCare.ai</a>
      </p>
    </div>
  );
}

function ContactUs() {
  return (
    <div className="contact-page">
      <h1>Contact Us</h1>
      <p>
        For support, partnership inquiries, or feedback about KinetiCare.ai, reach
        out using the information below or send a message using the form.
      </p>

      <h2>Support</h2>
      <p>
        Email: <a href="mailto:Dr.W@KinetiCare.ai">Dr.W@KinetiCare.ai</a>
      </p>

      <h2>Send a message</h2>
      <form
        onSubmit={(e) => {
          e.preventDefault();
          // minimal client-side behavior: open mail client with subject/body
          const form = e.currentTarget as HTMLFormElement;
          const formData = new FormData(form);
          const name = formData.get("name") || "";
          const email = formData.get("email") || "";
          const message = formData.get("message") || "";
          const mailto = `mailto:Dr.W@KinetiCare.ai?subject=${encodeURIComponent(
            `Website message from ${name}`
          )}&body=${encodeURIComponent(`From: ${name} <${email}>\n\n${message}`)}`;
          window.location.href = mailto;
        }}
      >
        <div style={{ marginBottom: 16 }}>
          <label>
            Name
            <input name="name" type="text" required />
          </label>
        </div>
        <div style={{ marginBottom: 16 }}>
          <label>
            Email
            <input name="email" type="email" required />
          </label>
        </div>
        <div style={{ marginBottom: 16 }}>
          <label>
            Message
            <textarea name="message" rows={6} required />
          </label>
        </div>
        <button type="submit">Send Message</button>
      </form>
    </div>
  );
}

function Home() {
  return (
    <>
      {/* Hero Section */}
      <div className="kineticare-hero">
        <div className="kineticare-logo-circle">
          <span
            role="img"
            aria-label="Hand Rehabilitation Logo"
            className="kineticare-logo"
            style={{ fontSize: "8rem" }}
          >
            🖐️
          </span>
        </div>
        <div className="kineticare-content">
          <h1 className="kineticare-title">KinetiCare.ai</h1>
          <h2 className="kineticare-subtitle">Guiding Prevention and Recovery</h2>
          <p className="kineticare-desc">
            Expert-designed hand and wrist rehabilitation exercises. One purposeful
            movement at a time—anytime, anywhere.
          </p>
          <nav style={{ marginTop: 12 }}>
            <Link to="/privacy-policy" className="privacy-link" style={{ marginRight: 16 }}>
              Privacy Policy
            </Link>
            <Link to="/contact" className="contact-link">
              Contact
            </Link>
          </nav>
        </div>
      </div>

      {/* Features Section */}
      <section className="features-section">
        <div className="features-container">
          <h2 className="section-title">Why Choose KinetiCare?</h2>
          <div className="features-grid">
            <div className="feature-card">
              <div className="feature-icon">🎯</div>
              <h3 className="feature-title">AI-Powered Feedback</h3>
              <p className="feature-description">
                Get real-time analysis of your exercise form with our advanced AI
                technology. Receive personalized feedback to optimize your recovery.
              </p>
            </div>
            <div className="feature-card">
              <div className="feature-icon">📱</div>
              <h3 className="feature-title">Exercise Anywhere</h3>
              <p className="feature-description">
                Access expert-designed rehabilitation exercises from any device.
                Practice at home, at work, or on the go.
              </p>
            </div>
            <div className="feature-card">
              <div className="feature-icon">📊</div>
              <h3 className="feature-title">Track Progress</h3>
              <p className="feature-description">
                Monitor your rehabilitation journey with detailed analytics and
                progress reports. Stay motivated with visual improvements.
              </p>
            </div>
            <div className="feature-card">
              <div className="feature-icon">👨‍⚕️</div>
              <h3 className="feature-title">Expert Guidance</h3>
              <p className="feature-description">
                Follow exercises designed by certified therapists and healthcare
                professionals with proven results.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Demo Video Section */}
      <section className="demo-section">
        <div className="demo-container">
          <h2 className="section-title">See It In Action</h2>
          <p className="kineticare-desc" style={{ marginBottom: "2rem" }}>
            Watch how KinetiCare.ai helps users perform rehabilitation exercises
            with real-time AI feedback and guidance.
          </p>
          <div className="demo-video-wrapper">
            <div className="demo-video-placeholder">
              <div className="demo-video-text">Hand & Wrist Exercises Demo</div>
            </div>
          </div>
          
          {/* Demo Images Grid */}
          <h3 className="section-title" style={{ fontSize: "2rem", marginTop: "4rem" }}>
            Exercise Examples
          </h3>
          <div className="demo-images-grid">
            <div className="demo-image-card">
              <div className="demo-image-overlay">
                <div className="demo-image-icon">🤚</div>
                <div className="demo-image-label">Finger Stretches</div>
              </div>
            </div>
            <div className="demo-image-card">
              <div className="demo-image-overlay">
                <div className="demo-image-icon">✊</div>
                <div className="demo-image-label">Grip Strength</div>
              </div>
            </div>
            <div className="demo-image-card">
              <div className="demo-image-overlay">
                <div className="demo-image-icon">👌</div>
                <div className="demo-image-label">Pinch Training</div>
              </div>
            </div>
            <div className="demo-image-card">
              <div className="demo-image-overlay">
                <div className="demo-image-icon">🔄</div>
                <div className="demo-image-label">Wrist Rotation</div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* How It Works Section */}
      <section className="how-it-works-section">
        <div className="demo-container">
          <h2 className="section-title">How It Works</h2>
          <div className="steps-container">
            <div className="step">
              <div className="step-number">1</div>
              <div className="step-content">
                <h3 className="step-title">Choose Your Exercise</h3>
                <p className="step-description">
                  Browse our library of expert-designed hand and wrist rehabilitation
                  exercises. Select the ones that match your recovery goals or follow
                  a recommended program.
                </p>
              </div>
            </div>
            <div className="step">
              <div className="step-number">2</div>
              <div className="step-content">
                <h3 className="step-title">Follow Video Guidance</h3>
                <p className="step-description">
                  Watch detailed video demonstrations with audio instructions. Our
                  clear, step-by-step guidance ensures you perform each movement
                  correctly and safely.
                </p>
              </div>
            </div>
            <div className="step">
              <div className="step-number">3</div>
              <div className="step-content">
                <h3 className="step-title">Get AI Feedback</h3>
                <p className="step-description">
                  Record your exercise attempts and receive instant AI-powered
                  feedback on your form and technique. Track your progress and
                  celebrate improvements over time.
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>
    </>
  );
}

function App() {
  return (
    <Router>
      <Routes>
        <Route path="/" element={<Home />} />
        <Route path="/privacy-policy" element={<PrivacyPolicy />} />
        <Route path="/contact" element={<ContactUs />} />
      </Routes>
    </Router>
  );
}

export default App;
