import { BrowserRouter as Router, Routes, Route, Link } from "react-router-dom";
import "./App.css";

function PrivacyPolicy() {
  return (
    <div className="privacy-policy">
      <h1>PRIVACY POLICY</h1>
      <p>
        Welcome to KinetiCare.ai, a digital rehabilitation platform designed to
        prevent injury and support upper extremity recovery through guided
        exercise videos, audio instructions, and AI-powered performance feedback.
        Your privacy is important to us. This Privacy Policy explains how we
        collect, use, and protect your information when you use our app.
      </p>
      <h2>Information We Collect</h2>
      <p>
        We collect the following types of information to provide and improve our
        services:
      </p>
      <ul>
        <li>
          <strong>User-Generated Content</strong>
          <ul>
            <li>Recorded exercise attempts (video and/or audio)</li>
            <li>Performance data generated by AI comparison tools</li>
          </ul>
        </li>
        <li>
          <strong>App Usage Data</strong>
          <ul>
            <li>
              Interaction logs (e.g., which exercises were viewed or completed)
            </li>
            <li>Device type, operating system, and app version</li>
          </ul>
        </li>
        <li>
          <strong>Optional Personal Information</strong>
          <ul>
            <li>
              Name, email address, or other identifiers if voluntarily provided
            </li>
          </ul>
        </li>
      </ul>
      <h2>Device Permissions</h2>
      <p>
        To enable core features of KinetiCare.ai, the app requests the following
        permissions:
      </p>
      <ul>
        <li>
          <strong>Camera Access:</strong> Required to record your exercise
          attempts for AI analysis and performance feedback. Camera access is
          only activated when you choose to record an exercise and is never used
          without your explicit action.
        </li>
        <li>
          <strong>Microphone Access:</strong> Required to capture audio
          instructions and provide audio-based feedback during exercises.
          Microphone access is only used during recording sessions that you
          initiate.
        </li>
      </ul>
      <p>
        You can manage these permissions through your device settings at any
        time. Denying these permissions may limit certain app functionality,
        such as the ability to receive personalized AI feedback on your exercise
        form.
      </p>
      <h2>How We Use Your Information</h2>
      <ul>
        <li>Deliver personalized exercise recommendations</li>
        <li>Provide AI-generated feedback on your performance</li>
        <li>Improve app functionality and user experience</li>
        <li>
          Communicate updates, support, or relevant health content (if opted in)
        </li>
      </ul>
      <h2>AI Analysis and Performance Grading</h2>
      <p>
        When you choose to record your exercise attempts, our AI tools analyze
        your movements against standard models to provide feedback and grading.
        These recordings are stored securely and are only used for your personal
        rehabilitation progress unless you give explicit consent for broader use
        (e.g., research or training).
      </p>
      <h2>Data Protection and Security</h2>
      <p>We implement industry-standard safeguards to protect your data, including:</p>
      <ul>
        <li>End-to-end encryption for video and audio uploads</li>
        <li>Secure storage of AI-generated performance data</li>
        <li>Role-based access controls for internal staff</li>
      </ul>
      <h2>Sharing of Protected Health Information (PHI)</h2>
      <p>
        We do not share any protected health information (PHI) with third parties
        without your explicit written consent. This includes:
      </p>
      <ul>
        <li>Exercise recordings</li>
        <li>AI-generated performance grades</li>
      </ul>
      <p>
        If you choose to share your data with a healthcare provider, caregiver, or
        research team, we will facilitate secure transfer only with your
        permission.
      </p>
      <h2>Your Rights and Choices</h2>
      <ul>
        <li>Access and review your data</li>
        <li>Request deletion of your recordings or personal information</li>
        <li>Withdraw consent for data sharing at any time</li>
        <li>Opt out of non-essential communications</li>
      </ul>
      <p>
        To exercise these rights, contact us at{" "}
        <a href="mailto:Dr.W@KinetiCare.ai">Dr.W@KinetiCare.ai</a>.
      </p>
      <h2>Children's Privacy</h2>
      <p>
        This app is not intended for use by individuals under the age of 13. We
        do not knowingly collect personal information from children without
        parental consent.
      </p>
      <h2>Changes to This Policy</h2>
      <p>
        We may update this Privacy Policy as our app evolves. We will notify you
        of significant changes via in-app alerts or email (if provided).
      </p>
      <h2>Contact Us</h2>
      <p>
        If you have questions or concerns about this Privacy Policy or your
        data, please reach out to us at{" "}
        <a href="mailto:Dr.W@KinetiCare.ai">Dr.W@KinetiCare.ai</a>
      </p>
    </div>
  );
}

function ContactUs() {
  return (
    <div className="contact-page" style={{ maxWidth: 800, margin: "40px auto", padding: 24 }}>
      <h1>Contact Us</h1>
      <p>
        For support, partnership inquiries, or feedback about KinetiCare.ai, reach
        out using the information below or send a message using the form.
      </p>

      <h2>Support</h2>
      <p>
        Email: <a href="mailto:Dr.W@KinetiCare.ai">Dr.W@KinetiCare.ai</a>
      </p>

      <h2>Send a message</h2>
      <form
        onSubmit={(e) => {
          e.preventDefault();
          // minimal client-side behavior: open mail client with subject/body
          const form = e.currentTarget as HTMLFormElement;
          const formData = new FormData(form);
          const name = formData.get("name") || "";
          const email = formData.get("email") || "";
          const message = formData.get("message") || "";
          const mailto = `mailto:Dr.W@KinetiCare.ai?subject=${encodeURIComponent(
            `Website message from ${name}`
          )}&body=${encodeURIComponent(`From: ${name} <${email}>\n\n${message}`)}`;
          window.location.href = mailto;
        }}
      >
        <div style={{ marginBottom: 8 }}>
          <label>
            Name
            <br />
            <input name="name" type="text" style={{ width: "100%" }} />
          </label>
        </div>
        <div style={{ marginBottom: 8 }}>
          <label>
            Email
            <br />
            <input name="email" type="email" style={{ width: "100%" }} />
          </label>
        </div>
        <div style={{ marginBottom: 8 }}>
          <label>
            Message
            <br />
            <textarea name="message" rows={6} style={{ width: "100%" }} />
          </label>
        </div>
        <button type="submit">Send</button>
      </form>
    </div>
  );
}

function Home() {
  return (
    <div className="kineticare-hero">
      <div className="kineticare-logo-circle">
        <span
          role="img"
          aria-label="Hand Rehabilitation Logo"
          className="kineticare-logo"
          style={{ fontSize: "8rem" }}
        >
          🖐️
        </span>
      </div>
      <div className="kineticare-content">
        <h1 className="kineticare-title">KinetiCare.ai</h1>
        <h2 className="kineticare-subtitle">Guiding Prevention and Recovery</h2>
        <p className="kineticare-desc">
          Expert-designed hand and wrist rehabilitation exercises. One purposeful
          movement at a time—anytime, anywhere.
        </p>
        <nav style={{ marginTop: 12 }}>
          <Link to="/privacy-policy" className="privacy-link" style={{ marginRight: 16 }}>
            Privacy Policy
          </Link>
          <Link to="/contact" className="contact-link">
            Contact
          </Link>
        </nav>
      </div>
    </div>
  );
}

function App() {
  return (
    <Router>
      <Routes>
        <Route path="/" element={<Home />} />
        <Route path="/privacy-policy" element={<PrivacyPolicy />} />
        <Route path="/contact" element={<ContactUs />} />
      </Routes>
    </Router>
  );
}

export default App;
